server:
  # En prod Railway, préfère ${PORT:2333}
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    # Garde Lavasrc si tu veux des résolutions Spotify -> SC/YT
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"
    # SUPPRIME (temporairement) le plugin YouTube si tu ne veux aucun chargement YT
    # - dependency: "dev.lavalink.youtube:youtube-plugin:1.14.0"

  server:
    password: "${LAVALINK_PASSWORD:youshallnotpass}"
    sources:
      youtube: false         # Désactive la source YT legacy
      bandcamp: false
      soundcloud: true       # Lecture SoundCloud active
      twitch: false
      vimeo: false
      http: false
      local: false

plugins:
  # Supprimer/neutraliser entièrement la section youtube
  # youtube:
  #   enabled: false
  #   allowSearch: false
  #   allowDirectVideoIds: false
  #   allowDirectPlaylistIds: false

  lavasrc:
    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false
      youtube: false        # Empêche Lavasrc d'utiliser YouTube comme sortie
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET}"
      countryCode: "FR"
      playlistLoadLimit: 6
      albumLoadLimit: 6
    providers:
      - "scsearch:%QUERY%"  # SoundCloud en premier
      # Optionnel: retire ytsearch si tu veux bannir toute dépendance YT
      # - "ytsearch:%QUERY%"

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
