server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"

  server:
    password: "${LAVALINK_PASSWORD:youshallnotpass}"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      http: false
      local: false

plugins:
  lavasrc:
    providers:
      - "scsearch:%ISRC%"      # Cherche d'abord avec ISRC (plus précis)
      - "scsearch:%QUERY%"     # Puis avec query standard
    
    sources:
      spotify: true
      applemusic: false        # ← DÉSACTIVÉ (playlists/albums non supportés)
      deezer: false
      yandexmusic: false
      youtube: false
    
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET}"
      countryCode: "FR"
      playlistLoadLimit: 6     # Max 6 playlists en parallèle
      albumLoadLimit: 6        # Max 6 albums en parallèle

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
